### ISSUE TITLE
Failed to activate the elastic-tabstops package

### ISSUE THREAD

**Issue by hax** [hax/atom-elastic-tabstops#19]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0-beta3 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.5
**Thrown From**: [elastic-tabstops](https://github.com/hax/atom-elastic-tabstops) package 1.1.3

### Stack Trace

Failed to activate the elastic-tabstops package

```
At Cannot read property 'updateTileNodes' of undefined

TypeError: Cannot read property 'updateTileNodes' of undefined
    at observeEditor (/Users/hax/repo/working/elastic-tabstops/lib/elastic-tabstops.js:43:24)
    at Workspace.observeTextEditors (/Applications/Atom Beta.app/Contents/Resources/app/src/workspace.js:717:15)
    at Object.activate (/Users/hax/repo/working/elastic-tabstops/lib/elastic-tabstops.js:18:18)
    at Package.module.exports.Package.activateNow (/Applications/Atom Beta.app/Contents/Resources/app/src/package.js:253:25)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/Applications/Atom Beta.app/Contents/Resources/app/src/package.js:99:21)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/Applications/Atom Beta.app/Contents/Resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom Beta.app/Contents/Resources/app/src/package-manager.js:645:40)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/package-manager.js:626:35
    at Config.module.exports.Config.transactAsync (/Applications/Atom Beta.app/Contents/Resources/app/src/config.js:346:24)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom Beta.app/Contents/Resources/app/src/package-manager.js:621:25)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom Beta.app/Contents/Resources/app/src/package-manager.js:603:52)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/atom-environment.js:843:36
```

### Commands

```
```

### Non-Core Packages

```
activate-power-mode 2.0.0 
atom-jade 0.3.0 
atom-ternjs 0.18.3 
atom-typescript 11.0.3 
blame 0.12.0 
coffee-refactor 0.7.0 
debug 0.0.1 
declarations 1.1.3 
declarations-js 1.0.2 
editorconfig 2.2.2 
elastic-tabstops 1.1.3 
file-icons 2.1.7 
hyperclick 0.0.40 
intentions 1.1.2 
js-refactor 0.7.5 
language-babel 2.65.0 
language-javascript-semantic 0.2.1 
line-ending-converter 1.3.2 
linter 2.1.4 
linter-php 1.3.2 
php-cs-fixer 4.1.0 
php-debug 0.2.4 
php-integrator-annotations 1.1.1 
php-integrator-autocomplete-plus 1.5.0 
php-integrator-base 2.1.12 
php-integrator-call-tips 1.2.1 
php-integrator-linter 1.3.0 
php-integrator-navigation 1.1.2 
php-integrator-refactoring 1.3.1 
php-integrator-tooltips 1.1.5 
refactor 0.11.4 
remote-sync 4.1.5 
Stylus 3.1.0 
```

**Comment by hax** [comment]
This is due to the new 1.19.0 rewrite of editor internal apis. Will be fixed (totally rewrite) next month.

**Comment by lillem4n** [comment]
I got this update of Atom now on Ubuntu... how is the rewrite going? I can not live without elastic tabstops. :)

**Comment by hax** [comment]
Start working on it.

See https://github.com/hax/atom-elastic-tabstops/tree/atom-1.19 
There are some bugs, but should work in normal cases.

**Comment by lillem4n** [comment]
Will this soon be released to the normal apm-thingie so I can install it directly from Atom and not from source?

**Comment by hax** [comment]
@lillem4n Sorry, I'm busy on some public presentations and other tech events recent weeks, so do not have enough time to release a stable version until 10th Sept.

**Comment by lillem4n** [comment]
That means it is comming! Most awesome! Thanks! \o/

**Comment by joy-yu** [comment]
催更！😂

**Comment by Smiler94** [comment]
Is that issue updated?

**Comment by charsen** [comment]
Is that issue updated?

**Comment by lillem4n** [comment]
I just updated Atom to 1.21 and it fail there as well.

**Comment by lillem4n** [comment]
Confirmed in 1.22 as well, if it helps. :)

**Comment by Spunky84** [comment]
The problem is still there, can you give us a short update on the progress?

**Comment by ghost** [comment]
Hello, guys!

Today I decided to install Atom for the first time to try it out. (Yesterday, actually, since now it’s over midnight.)

As I tend to do in the rare occasions I install a new text editor, I looked up for an *elastic tabstops* plugin in the hope of finally being able to make use of the concept.

I was thoroughly pleased to find this package, so I hurriedly installed it with high hopes. Unfortunately, it crashed on installation, and Atom linked me to this very issue that hasn’t been touched in several months.

I was quite frustrated about it; I really wanted to make use of elastic tabstops. But I did not give up, I decided to download the code from branch `atom-1.19` to see if it would work only to find out that it didn’t either.

That did not stop me, however. I put my quite lacking hacking skills to use and started to hack around the source.

I will stop narrating my little misadventures now as the rest is about what you’d expect. But, in conclusion, I was able to fix the broken version at `atom-1.19` to make it work on the newest version of Atom.

I will be attaching the [fixed files] in this very comment so you guys can rejoice too.

Here are the steps to use the fixed version correctly:

+ Download [the zip file from the `atom-1.19` branch](https://github.com/hax/atom-elastic-tabstops/archive/98f7a30fee301289c0117659aad4c14caad6cf9b.zip).
+ Unzip it as `elastic-tabstops-new` or some other meaningful name.
+ Download [the files from this comment][fixed files].
+ Put the files you’ve downloaded from this comment into the `lib` folder of the `elastic-tabstops-new` folder, replacing the existing files from that folder.
+ From the `elastic-tabstops-new` folder, run `npm install`.
+ Put the `elastic-tabstops-new` folder into the `~/.atom/packages` folder in your computer.
+ If you don’t have Atom open, open it.
+ If you do have Atom open, open the Command Palette and activate the `Window: Reload` command.
+ Rejoice!

[fixed files]: https://github.com/hax/atom-elastic-tabstops/files/1778167/lib.tar.gz

Edit:

I forgot to mention it, but there are still some issues around positioning the caret and toggling the feature off with the given keyboard shortcut, but I’m not sure if I’m knowledged enough to fix those. Either way, if I end up finding anything, I’ll be sure to share it here.

**Comment by hax** [comment]
Sorry, I do not have enough time for this project in last several months.

@Zambonifofex if you could submit your fixes as a PR, I would like to merge it and republish a new version.

**Comment by ghost** [comment]
@hax, done: #26.

**Comment by hax** [comment]
New version released, hope it work. Thank you @Zambonifofex

**Comment by BramEsposito** [comment]
Seems to sill have some issues: https://github.com/hax/atom-elastic-tabstops/issues/27
