### ISSUE TITLE
Uncaught TypeError: e.target.getModel is not a function

### ISSUE THREAD

**Issue by Tonylvv** [hax/atom-elastic-tabstops#21]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.20.1 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [elastic-tabstops](https://github.com/hax/atom-elastic-tabstops) package 1.2.0

### Stack Trace

Uncaught TypeError: e.target.getModel is not a function

```
At /Users/tonyMac/.atom/packages/elastic-tabstops/lib/elastic-tabstops.js:32

TypeError: e.target.getModel is not a function
    at /packages/elastic-tabstops/lib/elastic-tabstops.js:32:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1338:34)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:335:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -2:46.6.0 core:move-down (input.hidden-input)
     -2:44.6.0 core:move-left (input.hidden-input)
  2x -2:41.7.0 core:undo (input.hidden-input)
     -2:15.1.0 core:copy (div.package-readme.native-key-bindings)
     -1:25.8.0 snippets:next-tab-stop (input.hidden-input)
     -1:25.8.0 snippets:expand (input.hidden-input)
     -1:25.8.0 editor:indent (input.hidden-input)
  4x -1:23.5.0 core:backspace (input.hidden-input)
     -1:17.9.0 emmet:increment-number-by-01 (input.hidden-input)
  2x -1:15.1.0 core:backspace (input.hidden-input)
     -1:13.9.0 core:move-to-top (input.hidden-input)
  2x -1:12.9.0 core:move-down (input.hidden-input)
     -1:11.9.0 emmet:decrement-number-by-01 (input.hidden-input)
  2x -1:11.4.0 core:move-down (input.hidden-input)
  7x -0:59.7.0 core:backspace (input.hidden-input)
     -0:11 elastic-tabstops:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
atom-material-syntax 1.0.6 
atom-material-ui 2.0.4 
atom-ternjs 0.18.3 
elastic-tabstops 1.2.0 
emmet 2.4.3 
file-icons 2.1.12 
jsformat 0.9.3 
language-vue 0.23.1 
minimap 4.29.7 
open-in-browsers 0.0.30 
platformio-ide-terminal 2.6.0 
react 0.16.2 
script 3.16.0 
```

**Comment by finaldesignrb** [comment]
Thanks for logging this, Tony. Same problem Arch Linux with latest 1.20 Atom text editor.
