### ISSUE TITLE
Uncaught TypeError: Cannot read property 'updateTileNodes' of undefined

### ISSUE THREAD

**Issue by meteortears** [hax/atom-elastic-tabstops#23]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.0-beta0 x64
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: [elastic-tabstops](https://github.com/hax/atom-elastic-tabstops) package 1.2.0

### Stack Trace

Uncaught TypeError: Cannot read property 'updateTileNodes' of undefined

```
At C:\Users\Administrator\.atom\packages\elastic-tabstops\lib\elastic-tabstops.js:141

TypeError: Cannot read property 'updateTileNodes' of undefined
    at enable (/packages/elastic-tabstops/lib/elastic-tabstops.js:141:24)
    at ~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/workspace.js:729:22
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at ~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/workspace.js:583:34
    at ~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/workspace.js:584:19
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PaneContainer.didAddPaneItem (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/pane-container.js:270:24)
    at PaneContainer.didAddPane (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/pane-container.js:242:18)
    at Pane.setContainer (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/pane.js:137:23)
    at PaneAxis.module.exports.PaneAxis.addChild (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/pane-axis.js:154:19)
    at PaneAxis.module.exports.PaneAxis.insertChildAfter (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/pane-axis.js:225:25)
    at Pane.split (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/pane.js:1111:39)
    at Pane.splitRight (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/pane.js:1059:23)
    at HTMLElement.pane:split-right-and-copy-active-item (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/register-default-commands.js:269:38)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/command-registry.js:388:36)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/command-registry.js:273:23)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/atom-environment.js:1399:34)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/application-delegate.js:348:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:21.9.0 pane:split-right-and-copy-active-item (div.line)
     -0:15.8.0 tabs:split-right (div.title.icon.js-icon.medium-yellow.temp)
     -0:04.7.0 pane:split-right-and-copy-active-item (ul.list-inline.tab-bar.inset-panel)
```

### Non-Core Packages

```
advanced-new-file 0.5.0 
advanced-open-file 0.16.7 
atom-html-preview 0.2.2 
atom-live-server 2.2.0 
atom-minify 0.8.0 
atomic-chrome 0.3.3 
autocomplete-modules 1.8.0 
autocomplete-paths 2.12.1 
autoprefixer 3.7.1 
busy-signal 1.4.3 
color-picker 2.2.5 
css-snippets 1.1.0 
csscomb 0.3.1 
docblockr 0.13.2 
editor-stats 0.17.0 
elastic-tabstops 1.2.0 
emmet 2.4.3 
file-icons 2.1.13 
file-types 0.5.5 
git-log 0.4.1 
git-time-machine 1.5.9 
grunt-runner 0.14.0 
hyperclick 0.1.5 
intentions 1.1.5 
jade-beautify 0.1.5 
javascript-snippets 1.2.1 
jquery-snippets 11.0.0 
js-hyperclick 1.12.1 
jsformat 0.9.3 
jshint 1.8.6 
keyboard-localization 1.5.0 
language-cshtml 0.3.0 
language-jade 0.7.2 
language-javascript-jsx 0.3.7 
linter 2.2.0 
linter-csslint 2.0.0 
linter-jshint 3.1.6 
linter-sass-lint 1.8.3 
linter-ui-default 1.6.10 
markdown-format 2.5.1 
markdown-preview-plus 2.4.16 
markdown-toc 0.4.2 
minimap 4.29.7 
open-in-browsers 0.0.30 
pigments 0.40.2 
pretty-json 1.6.4 
project-manager 3.3.5 
react-snippets 1.0.0 
regex-railroad-diagram 0.19.4 
release-notes 0.53.0 
Remote-FTP 1.3.1 
seti-icons 1.5.4 
seti-ui 1.9.0 
simplified-chinese-menu 5.3.4 
sort-lines 0.18.0 
sync-settings 0.8.3 
tab-switcher 1.5.6 
tool-bar 1.1.0 
tree-view-finder 0.2.1 
tree-view-git-status 1.4.0 
```

**Comment by hax** [comment]
Duplicated #19
