### ISSUE TITLE
At Cannot read property 'updateTileNodes' of undefined

### ISSUE THREAD

**Issue by qq897425998** [hax/atom-elastic-tabstops#25]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [elastic-tabstops](https://github.com/hax/atom-elastic-tabstops) package 1.2.0

### Stack Trace

Failed to activate the elastic-tabstops package

```
At Cannot read property 'updateTileNodes' of undefined

TypeError: Cannot read property 'updateTileNodes' of undefined
    at enable (/packages/elastic-tabstops/lib/elastic-tabstops.js:141:24)
    at Workspace.observeTextEditors (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:725:15)
    at Object.activate (/packages/elastic-tabstops/lib/elastic-tabstops.js:30:18)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:253:25)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:215:40)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:690:42)
    at config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:665:36)
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/config.js:367:24)
    at PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:663:23)
    at PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:646:50)
    at /Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:854:36
```

### Commands

```
     -1:55.6.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
atom-react-autocomplete 0.1.10 
autocomplete-js-import 1.4.0 
autocomplete-modules 1.8.0 
elastic-tabstops 1.2.0 
language-babel 2.80.3 
language-javascript-jsx 0.3.7 
nuclide 0.270.0 
nuclide-format-js 0.0.41 
platformio-ide-terminal 2.7.0 
react-es6-snippets 0.3.0 
```

**Comment by hax** [comment]
duplicated as #19
