### ISSUE TITLE
Uncaught TypeError: Cannot read property '_updateTileNodes' of undefined

### ISSUE THREAD

**Issue by BramEsposito** [hax/atom-elastic-tabstops#27]
[Enter steps to reproduce:]

1. Install Atom
2. Install Elastic tabstops package
3. open a file with tabs e.g.
```
one two
1 2
```
4. in the menu, go to Packages > Elastic tabstops > toggle
5. Error is also thrown after restarting Atom

**Atom**: 1.25.1 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.12.6
**Thrown From**: [elastic-tabstops](https://github.com/hax/atom-elastic-tabstops) package 1.3.1

### Stack Trace

Uncaught TypeError: Cannot read property '_updateTileNodes' of undefined

```
At /Users/bram/.atom/packages/elastic-tabstops/lib/elastic-tabstops.js:106

TypeError: Cannot read property '_updateTileNodes' of undefined
    at disable (/packages/elastic-tabstops/lib/elastic-tabstops.js:106:7)
    at /packages/elastic-tabstops/lib/elastic-tabstops.js:46:5)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:384:49)
    at CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:273:23)
    at AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1343:25)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:339:53)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:197:7)
```

### Commands

```
     -1:44.7.0 core:backspace (input.hidden-input)
     -1:41.8.0 core:confirm (input.hidden-input)
     -0:37.9.0 elastic-tabstops:toggle (input.hidden-input)
```

### Non-Core Packages

```
elastic-tabstops 1.3.1 
```

**Comment by daanx** [comment]
I have the same problem. the package hasn't been usable since version 1.19 (? I think) because of these errors :-(

**Comment by DBattou** [comment]
Same issue here

**Comment by graemeg** [comment]
Two years on, and still no movement on this issue? :-(

**Comment by hax** [comment]
Unfortunately I do not have much time on this package now, if anyone could commit PR to fix this I would like to merge it asap.

**Comment by ThatXliner** [comment]
Maybe we can just delete 
https://github.com/hax/atom-elastic-tabstops/blob/956a0a3fd92e3d27364579c70db70c0aea5f119a/lib/elastic-tabstops.js#L105-L109
