### ISSUE TITLE
Uncaught TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by laigq2015** [hax/atom-elastic-tabstops#5]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.10.0-dev
**Electron Version**: 0.37.8
**System**: Kali GNU/Linux
**Thrown From**: [elastic-tabstops](https://github.com/hax/atom-elastic-tabstops) package, v1.1.1
### Stack Trace

Uncaught TypeError: Cannot convert undefined or null to object

```
At /home/wiwry/.atom/packages/elastic-tabstops/lib/elastic-tabstops.js:96

TypeError: Cannot convert undefined or null to object
  at update (/home/wiwry/.atom/packages/atom-elastic-tabstops/lib/elastic-tabstops.js:96:17)
  at LinesComponent.c.updateTileNodes (/home/wiwry/.atom/packages/atom-elastic-tabstops/lib/elastic-tabstops.js:62:3)
  at LinesComponent.module.exports.TiledComponent.updateSync (/usr/local/share/atom/resources/app.asar/src/tiled-component.js:30:12)
  at TextEditorComponent.module.exports.TextEditorComponent.updateSyncPreMeasurement (/usr/local/share/atom/resources/app.asar/src/text-editor-component.js:265:34)
  at TextEditorComponent.module.exports.TextEditorComponent.updateSync (/usr/local/share/atom/resources/app.asar/src/text-editor-component.js:205:12)
  at /usr/local/share/atom/resources/app.asar/src/text-editor-component.js:324:28
  at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/usr/local/share/atom/resources/app.asar/src/view-registry.js:221:9)
  at /usr/local/share/atom/resources/app.asar/src/view-registry.js:3:61

```
### Commands

```
```
### Config

``` json
{
  "core": {
    "allowPendingPaneItems": false,
    "disabledPackages": [
      "terminal-plus",
      "Zen"
    ],
    "packagesWithKeymapsDisabled": [],
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
elastic-tabstops, v1.1.1 (active)
atom-html-preview, v0.1.22 (active)
atom-material-syntax, v0.4.6 (active)
atom-material-ui, v1.2.13 (active)
atom-minify, v0.7.5 (active)
atom-ternjs, v0.14.2 (active)
autocomplete-en-cn, v0.4.0 (active)
autocomplete-java, v1.2.5 (inactive)
autocomplete-js-import, v1.0.1 (active)
autocomplete-json, v5.1.0 (active)
autocomplete-paths, v1.0.2 (active)
autocomplete-php, v0.3.7 (active)
emmet, v2.4.3 (active)
file-icons, v1.7.17 (active)
git-control, v0.8.2 (inactive)
git-plus, v5.16.2 (inactive)
markdown-preview-plus, v2.4.0 (active)
minimap, v4.24.7 (active)
open-recent, v5.0.0 (active)
project-plus, v0.9.0 (active)
script, v3.8.2 (inactive)
sync-settings, v0.7.2 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (inactive)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.38.1 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.240.1 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.0 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.0 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by hax** [comment]
Thank you for report. I will investigate it soon.

**Comment by hax** [comment]
This bug is due to Atom 1.9.0 change some inner API...

**Comment by lillem4n** [comment]
I'm getting this on Atom 1.9.4 and elastic-tabstops v1.1.2. Will a 1.1.3 or something be released soon to fix this?

This might be the most important plugin for Atom for me, it is awesome! <3

**Comment by lillem4n** [comment]
False alarm! Atom needed a restart after the 1.1.1 -> 1.1.2 update.
